apiVersion: v1
kind: ConfigMap
metadata:
  name: martech-config
  namespace: martech
data:
  MONGO_DB: martech_vault
  REDIS_TTL_SECONDS: "300"
  ES_INDEX_PREFIX: martech
  LOG_LEVEL: info
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
