apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: martech
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1   # change to your AWS region
      auth:
        jwt:
          serviceAccountRef:
            name: martech-sa
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: martech-secrets
  namespace: martech
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: martech-secrets      # creates/updates the K8s Secret of this name
    creationPolicy: Owner
  data:
    - secretKey: MONGO_URI
      remoteRef:
        key: martech/prod
        property: MONGO_URI
    - secretKey: REDIS_URL
      remoteRef:
        key: martech/prod
        property: REDIS_URL
    - secretKey: ES_HOSTS
      remoteRef:
        key: martech/prod
        property: ES_HOSTS
    - secretKey: ES_API_KEY
      remoteRef:
        key: martech/prod
        property: ES_API_KEY
