# DO NOT commit real values — use External Secrets Operator or AWS Secrets Manager
apiVersion: v1
kind: Secret
metadata:
  name: martech-secrets
  namespace: martech
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongo-svc:27017"
  REDIS_URL: "redis://redis-svc:6379/0"
  ES_HOSTS: '["http://elasticsearch-svc:9200"]'
  ES_API_KEY: ""
