apiVersion: v1
kind: Service
metadata:
  name: martech-api-svc
  namespace: martech
spec:
  selector:
    app: martech-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: martech-api-ingress
  namespace: martech
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: martech.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: martech-api-svc
                port:
                  number: 80
